services:
  # api_server:
  #   build: .
  #   container_name: 'API_SERVER'
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     NODE_ENV: production
  #   volumes:
  #     - ./:/app:cached

  db_app:
    image: postgres:17
    container_name: DATABASE
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: ion-record
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_test:
    image: postgres:17
    container_name: DATABASE_TEST
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: ion-record
    volumes:
      - database_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  database_data:
  database_test_data:
  # api_data:
