services:
  db_app:
    image: postgres:17
    container_name: DATABASE
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  db_test:
    image: postgres:17
    container_name: DATABASE_TEST
    environment:
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_DATABASE}
    volumes:
      - database_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  database_data:
  database_test_data:

networks:
  app-network:
    driver: bridge
