services:
  api_server:
    build: .
    container_name: 'API_SERVER'
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
    volumes:
      - ./:/app

  database:
    image: postgres:17
    container_name: DATABASE
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: ion-record
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
  # api_data:
